server:
  port: 80

spring:
  datasource:
    url: secrets.MYSQL_CONNECTION
    username: secrets.MYSQL_ADMIN
    password: secrets.MYSQL_PASSWORD
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: false
    locations: classpath:migration
    outOfOrder: true
    table: schema_version
    fail-on-missing-locations: true

logging:
  level:
    root: INFO
    com.example.multitenancypoc: DEBUG
