server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/metadata?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
    hibernate:
      ddl-auto: none
    open-in-view: false
  flyway:
    enabled: false
    locations: classpath:migration
    outOfOrder: true
    table: schema_version
    fail-on-missing-locations: true
